<?php
/**
 * Blog English language file.
 *
 */
$french = array(
	'blog' => "XXXXchanged on 1.8 (1.7=Blog)XXXXBlogsXXXXBlog",	'blog:blogs' => "XXXXnew on 1.8XXXXBlogsXXXXgoogle:Blogs",	'blog:revisions' => "XXXXnew on 1.8XXXXRevisionsXXXXgoogle:Révisions",	'blog:archives' => "XXXXnew on 1.8XXXXArchivesXXXXgoogle:Archives",	'blog:blog' => "XXXXnew on 1.8XXXXBlogXXXXgoogle:Blog",	'item:object:blog' => "XXXXchanged on 1.8 (1.7=Blog posts)XXXXBlogsXXXXArticles du blog",	'blog:title:user_blogs' => "XXXXnew on 1.8XXXX%s's BlogsXXXXgoogle:% s de Blogs",	'blog:title:all_blogs' => "XXXXnew on 1.8XXXXAll Site BlogsXXXXgoogle:Tous les blogs du site",	'blog:title:friends' => "XXXXnew on 1.8XXXXFriends' BlogsXXXXgoogle:Amis Blogs",	'blog:group' => "Blog de groupe",	'blog:enableblog' => "XXXXnew on 1.8XXXXEnable group blogXXXXgoogle:blog de groupe Activer",	'blog:write' => "XXXXnew on 1.8XXXXWrite a blog postXXXXgoogle:Donnez un billet de blog",	// Editing
	'blog:add' => "XXXXnew on 1.8XXXXAdd blog postXXXXgoogle:Ajouter un blog",	'blog:edit' => "XXXXnew on 1.8XXXXEdit blog postXXXXgoogle:Modifier le message blog",	'blog:excerpt' => "XXXXnew on 1.8XXXXExcerptXXXXgoogle:Extrait",	'blog:body' => "XXXXnew on 1.8XXXXBodyXXXXgoogle:Organe",	'blog:save_status' => "XXXXnew on 1.8XXXXLast saved: XXXXgoogle:Dernier enregistrement:",	'blog:never' => "XXXXchanged on 1.8 (1.7=never)XXXXNeverXXXXjamais",	// Statuses
	'blog:status' => "XXXXnew on 1.8XXXXStatusXXXXgoogle:Statut",	'blog:status:draft' => "XXXXnew on 1.8XXXXDraftXXXXgoogle:Projet de",	'blog:status:published' => "XXXXnew on 1.8XXXXPublishedXXXXgoogle:Publié",	'blog:status:unsaved_draft' => "XXXXnew on 1.8XXXXUnsaved DraftXXXXgoogle:Projet non enregistrées",	'blog:revision' => "XXXXnew on 1.8XXXXRevisionXXXXgoogle:Révision",	'blog:auto_saved_revision' => "XXXXnew on 1.8XXXXAuto Saved RevisionXXXXgoogle:Auto enregistrés des versions",	// messages
	'blog:message:saved' => "XXXXnew on 1.8XXXXBlog post saved.XXXXgoogle:Blog post sauvé.",	'blog:error:cannot_save' => "XXXXnew on 1.8XXXXCannot save blog post.XXXXgoogle:Impossible d'enregistrer blog.",	'blog:error:cannot_write_to_container' => "XXXXnew on 1.8XXXXInsufficient access to save blog to group.XXXXgoogle:L'accès insuffisant à sauver blog de groupe.",	'blog:error:post_not_found' => "XXXXnew on 1.8XXXXThis post has been removed, is invalid, or you do not have permission to view it.XXXXgoogle:Ce message a été supprimé, n'est pas valide, ou vous n'avez pas la permission de le voir.",	'blog:messages:warning:draft' => "XXXXnew on 1.8XXXXThere is an unsaved draft of this post!XXXXgoogle:Il s'agit d'un projet non enregistré de ce post!",	'blog:edit_revision_notice' => "XXXXnew on 1.8XXXX(Old version)XXXXgoogle:(Ancienne version)",	'blog:message:deleted_post' => "XXXXnew on 1.8XXXXBlog post deleted.XXXXgoogle:Blog post supprimé.",	'blog:error:cannot_delete_post' => "XXXXnew on 1.8XXXXCannot delete blog post.XXXXgoogle:Impossible de supprimer le billet de blog.",	'blog:none' => "XXXXnew on 1.8XXXXNo blog postsXXXXgoogle:Aucun blog",	'blog:error:missing:title' => "XXXXnew on 1.8XXXXPlease enter a blog title!XXXXgoogle:S'il vous plaît entrer un titre du blog!",	'blog:error:missing:description' => "XXXXnew on 1.8XXXXPlease enter the body of your blog!XXXXgoogle:S'il vous plaît entrer dans le corps de votre blog!",	'blog:error:cannot_edit_post' => "XXXXnew on 1.8XXXXThis post may not exist or you may not have permissions to edit it.XXXXgoogle:Ce message peut ne pas exister ou que vous n'ayez pas les autorisations pour le modifier.",	'blog:error:revision_not_found' => "XXXXnew on 1.8XXXXCannot find this revision.XXXXgoogle:Vous ne trouvez pas cette révision.",	// river
	'blog:river:create' => "XXXXchanged on 1.8 (1.7=a new blog post titled)XXXXpublished a blog postXXXXun nouvel article intitulé",	'river:commented:object:blog' => "XXXXnew on 1.8XXXXthe blogXXXXgoogle:le blog",	// widget
	'blog:widget:description' => "XXXXchanged on 1.8 (1.7=This widget displays your latest blog entries.)XXXXDisplay your latest blog postsXXXXCe widget affiche votre dernier article de blog.",	'blog:moreblogs' => "Plus d'articles du blog",	'blog:numbertodisplay' => "Nombre d'articles du blog à afficher",	'blog:noblogs' => "XXXXnew on 1.8XXXXNo blog postsXXXXgoogle:Aucun blog",);
add_translation("fr", $french);