<?php
/**
 * Elgg developer tools English language file.
 *
 */
$french = array(
	// menu
	'admin:developers' => "XXXXnew on 1.8XXXXDevelopersXXXXgoogle:Les développeurs",	'admin:developers:settings' => "XXXXnew on 1.8XXXXDeveloper SettingsXXXXgoogle:Développeur Paramètres",	'admin:developers:preview' => "XXXXnew on 1.8XXXXTheming PreviewXXXXgoogle:Thématisation Extrait",	// settings
	'developers:label:simple_cache' => "XXXXnew on 1.8XXXXUse simple cacheXXXXgoogle:Utiliser le cache simple",	'developers:help:simple_cache' => "XXXXnew on 1.8XXXXTurn off the file cache when developing. Otherwise, changes to your views (including css) will be ignored.XXXXgoogle:Désactiver le cache de fichiers lors de l'élaboration. Sinon, les modifications à votre point de vue (y compris les css) seront ignorées.",	'developers:label:view_path_cache' => "XXXXnew on 1.8XXXXUse view path cacheXXXXgoogle:Utiliser le cache chemin vue",	'developers:help:view_path_cache' => "XXXXnew on 1.8XXXXTurn this off when developing. Otherwise, new views in your plugins will not be registered.XXXXgoogle:Désactivez cette option lors de l'élaboration. Sinon, de nouvelles vues dans vos plugins ne seront pas enregistrés.",	'developers:label:debug_level' => "XXXXnew on 1.8XXXXTrace levelXXXXgoogle:Niveau de trace",	'developers:help:debug_level' => "XXXXnew on 1.8XXXXThis controls the amount of information logged. See elgg_log() for more information.XXXXgoogle:Ce contrôle la quantité d'informations enregistrées. Voir elgg_log () pour plus d'informations.",	'developers:label:display_errors' => "XXXXnew on 1.8XXXXDisplay fatal PHP errorsXXXXgoogle:Affichage des erreurs fatales PHP",	'developers:help:display_errors' => "XXXXnew on 1.8XXXXBy default, Elgg's .htaccess file supresses the display of fatal errors.XXXXgoogle:Par défaut, le fichier htaccess Elgg. Supprime l'affichage des erreurs fatales.",	'developers:debug:off' => "XXXXnew on 1.8XXXXOffXXXXgoogle:Off",	'developers:debug:error' => "XXXXnew on 1.8XXXXErrorXXXXgoogle:Erreur",	'developers:debug:warning' => "XXXXnew on 1.8XXXXWarningXXXXgoogle:Avertissement",	'developers:debug:notice' => "XXXXnew on 1.8XXXXNoticeXXXXgoogle:Avis",	// theme preview
	'theme_preview:buttons' => "XXXXnew on 1.8XXXXButtonsXXXXgoogle:Boutons",	'theme_preview:components' => "XXXXnew on 1.8XXXXComponentsXXXXgoogle:Composants",	'theme_preview:forms' => "XXXXnew on 1.8XXXXFormsXXXXgoogle:Formulaires",	'theme_preview:grid' => "XXXXnew on 1.8XXXXGridXXXXgoogle:Grid",	'theme_preview:icons' => "XXXXnew on 1.8XXXXIconsXXXXgoogle:Icônes",	'theme_preview:modules' => "XXXXnew on 1.8XXXXModulesXXXXgoogle:Modules",	'theme_preview:navigation' => "XXXXnew on 1.8XXXXNavigationXXXXgoogle:Navigation",	'theme_preview:typography' => "XXXXnew on 1.8XXXXTypographyXXXXgoogle:Typographie",);
add_translation("fr", $french);